--====================================================== 
--Patrick Foy
--CIS332: Database and SQL
--UNIT 2, CHAPTER 3 Assignment
--======================================================

DROP TABLE CATEGORY PURGE;

CREATE TABLE CATEGORY (CatCode VARCHAR2 (2), CatDesc VARCHAR2 (10));

DESC CATEGORY

CREATE TABLE EMPLOYEES (Emp# NUMBER (5), Lastname VARCHAR2 (15), Firstname VARCHAR2 (15), Job_Class VARCHAR2 (4));

DESC EMPLOYEES

ALTER TABLE EMPLOYEES ADD (EmpDate DATE DEFAULT SYSDATE, EndDate DATE);

DESC EMPLOYEES

ALTER TABLE EMPLOYEES MODIFY (Job_Class VARCHAR2 (2));

DESC EMPLOYEES

ALTER TABLE EMPLOYEES DROP COLUMN EndDate;

DESC EMPLOYEES

RENAME EMPLOYEES TO JL_EMPS;

DESC JL_EMPS

CREATE TABLE BOOK_PRICING AS (SELECT ISBN AS "ID", Cost, Retail, Category FROM BOOKS);

DESC BOOK_PRICING

ALTER TABLE BOOK_PRICING SET UNUSED (Category);

DESC BOOK_PRICING

SELECT * 
FROM BOOK_PRICING;

TRUNCATE TABLE BOOK_PRICING;

DESC BOOK_PRICING

DROP TABLE BOOK_PRICING PURGE;

SELECT DISTINCT ORIGINAL_NAME,OPERATION,CREATETIME, DROPTIME
FROM recyclebin;

DROP TABLE JL_EMPS;

SELECT DISTINCT ORIGINAL_NAME,OPERATION,CREATETIME, DROPTIME
FROM recyclebin;